### ISSUE TITLE
MultiBench result is way too much different from what's reported on the paper

### ISSUE THREAD

**Issue by pospow** [pliang279/FactorCL#3]
**Local run(best score)**
accuracy | MOSEI | MOSI | sarcasm | humor
FactorCL-SUP | 71.05 | 51.75 | 55.07 | 49.53
SupCon | 74.61 | 51.17 | 52.17 | 50.85

**Reported**
accuracy | MOSEI | MOSI | sarcasm | humor
FactorCL-SUP | 77.34 | 70.69 | 59.42 | 54.44
SupCon | 72.71 | 47.23 | 46.38 | 52.36

Hi authors,

I ran the notebook file(multibench_example.ipynb) without any modification and found significant gap compared to what's reported on the paper.

The numbers I wrote in the local run result are actually the best scores I could get from 5 to 10 independent runs, and the deviations were quite large ranging from 3 to 5% (compared to std of 0.2~ 2.8% from the paper)

Any idea what could went wrong with it? 
Other experiments including Synthetic, IRFL were found to be reproducible.

Thanks in advance.

**Comment by zihaod** [comment]
Hi!

I would like to apologize for the issues you found, as the code was actually outdated. We updated the code and notebooks recently, so you can try the new versions for experiments. 

Please let us know if you still find any issues and thanks for your feedback!
